### ISSUE TITLE
Add stakeTo() 

### ISSUE THREAD

**Issue by pi0neerpat** [graphprotocol/token-distribution#35]
As an indexer, I would like to be able to stake tokens to a separate indexer address, instead of using the Token Lock address.

This will prevent me from having to unstake, switch, and restake to a new address later once the tokens become unlocked. I am already unstaked now, so I would prefer not having to do it again.

If there is a better solution for this I'm open to other ideas.

**Comment by davekaj** [comment]
Hey @pi0neerpat 

Good idea. I wish we could do this for you, but it has a bad consequence. If we allowed `stakeTo()` - it effectively exits the tokens from the token lock wallet. These tokens would then be in a new address, and they could unstake all of them, and the token lock wallets locking period would be completely avoided. 

I believe all indexers are under a 1 year lock, then for a year the tokens unlocking 1/12 every month. 

So at the time of 1 year, 1 month, an indexer with 1 million tokens will be able to withdraw 83,333 GRT. So they can either:
- keep all 1MM tokens staked and keep earning rewards.
- Withdraw the 83,333 and wait 28 days, take that GRT and do whatever they want with it. Leave the other ~917,000 GRT staked until the next month. When they can withdraw another 83K.

It is true that it is slightly more convenient to have all tokens in an EOA rather than the token lock wallet when the tokens start to become unlocked. But I believe with the linear release, it gives indexers a good amount of room to maneuver. If you need to exit rewards, take the 83,333 each month. If you want to keep staking, leave it in the token lock wallet. 

What do you think?

**Comment by pi0neerpat** [comment]
That makes sense, since unstaked tokens go back to the indexer,  not the
token lock.

I'll start the forum on Token Lock sunset, so no need to reply here. Just
getting some thoughts out.

I have a decision to make-

Option A) start a new indexer, with a very limited delegation cap since
I'll only have 100k GRT

Option B)  Restart my existing token locked indexer. Continue to be subject
to the token lock.

I want to make the most of my opportunity now, since I'm already forced to
take such a big loss. Would be very helpful to understand if there is
already plan on how indexers can escape the token lock during the sunset
period.

**Comment by davekaj** [comment]
great, we can continue the discussion in the forum!
